#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift File.expand_path('../lib', __dir__)
require 'json'
require 'travis/build'

payload = JSON.parse(STDIN.read)
puts Travis::Build.script(payload).compile(true)
