#!/bin/bash

set -ev

app_name="web"
local_image="travisbuild_$app_name" # Docker Compose removes dashes and expects the name to end with the build app name
quay_image=quay.io/travisci/travis-build;

docker-compose build "$app_name";
docker login -u="$QUAY_ROBOT_HANDLE" -p="$QUAY_ROBOT_TOKEN" quay.io;
docker images;

docker tag $local_image $quay_image:$TRAVIS_BRANCH;
docker push $quay_image:$TRAVIS_BRANCH;

docker tag $local_image $quay_image:${TRAVIS_COMMIT:0:7};
docker push $quay_image:${TRAVIS_COMMIT:0:7};

if [ ${TRAVIS_BRANCH} = "master" ]; then
  docker tag $local_image $quay_image:latest;
  docker push $quay_image:$TRAVIS_BRANCH;
fi

exit 0;
