#!/bin/bash

set -ev

quay_image=quay.io/travisci/travis-build
tag_name=$(echo "$TRAVIS_BRANCH" | sed -e "s/\\//-/g")

image_and_tag="${quay_image}:${tag_name}"

unset DOCKER_CERT_PATH
unset DOCKER_HOST
unset DOCKER_TLS
unset DOCKER_TLS_VERIFY

docker build -t "${quay_image}:${tag_name}" .

docker images

docker tag "${image_and_tag}" "${quay_image}:${TRAVIS_COMMIT:0:7}"

docker login -u="${QUAY_ROBOT_HANDLE}" -p="${QUAY_ROBOT_TOKEN}" quay.io

docker push "${image_and_tag}"
docker push "${quay_image}:${TRAVIS_COMMIT:0:7}"

if [[ "${TRAVIS_BRANCH}" == "master" ]]; then
  docker tag "${image_and_tag}" "${quay_image}:latest"
  docker push "${quay_image}:${TRAVIS_BRANCH}"
fi

exit 0
