#!/usr/bin/env ruby
# frozen_string_literal: true
require 'net/http'

def go_version
  res = Net::HTTP.get URI('https://go.dev/dl/')
  start = res.index '/dl/go'
  if start
    start += '/dl/'.length
    last = res.index '"', start
    res[start, last- start]&.match(/go\d+\.\d+\.?\d*/)&.to_s[2..]
  end
end

File.write('/tmp/go-version',go_version)
