#!/usr/bin/env ruby
# frozen_string_literal: true
require 'net/http'

def go_version
  res = Net::HTTP.get URI('https://go.dev/VERSION?m=text')
  res.match(/(?<=go).*/)
end

File.write('/tmp/go-version',go_version)
