#!/usr/bin/env bash
set -o errexit

main() {
  local top
  top="$(git rev-parse --show-toplevel)"

  [[ "${DOCKER_CLIENT_CONFIG_ENC_KEY}" ]] || {
    log "missing \${DOCKER_CLIENT_CONFIG_ENC_KEY}"
    exit 0
  }

  [[ "${DOCKER_CLIENT_CONFIG_ENC_IV}" ]] || {
    log "missing \${DOCKER_CLIENT_CONFIG_ENC_IV}"
    exit 0
  }

  [[ "${DOCKER_CLIENT_CONFIG_URL}" ]] || {
    log "missing \${DOCKER_CLIENT_CONFIG_URL}"
    exit 0
  }

  local tbz_enc="${top}/tmp/docker.tar.bz2.enc"
  mkdir -p "${top}/tmp"

  log 'fetching client config'
  curl -fsSL -o "${tbz_enc}" "${DOCKER_CLIENT_CONFIG_URL}"

  log "decrypting ${tbz_enc}"
  openssl aes-256-cbc \
    -d \
    -K "${DOCKER_CLIENT_CONFIG_ENC_KEY}" \
    -iv "${DOCKER_CLIENT_CONFIG_ENC_IV}" \
    -in "${tbz_enc}" \
    -out "${top}/tmp/docker.tar.bz2" >&2

  log "expanding ${top}/tmp/docker.tar.bz2"
  mkdir -p "${top}/.docker"
  tar -C "${top}/.docker" --strip-components=1 \
    -xf "${top}/tmp/docker.tar.bz2" >&2

  echo "export DOCKER_CERT_PATH='${top}/.docker';"
  echo "export DOCKER_TLS_VERIFY=1;"
  echo "export DOCKER_TLS=1;"
}

log() {
  printf "handle-docker-config: %s\\n" "${*}" >&2
}

main "${@}"
