#!/usr/bin/env bash
set -o errexit

main() {
  cd "$(dirname "$0")/.."
  : "${PORT:=5000}"
  : "${RACK_ENV:=development}"

  local cmd=(
    bundle exec je puma -I lib
    -p "${PORT}"
    -t "${PUMA_MIN_THREADS:-8}:${PUMA_MAX_THREADS:-12}"
    -w "${PUMA_WORKERS:-2}"
  )

  if [[ "${RACK_ENV}" == development && ! "${DISABLE_RERUN}" ]]; then
    cmd=(rerun -p '**/*.{rb,ru}' -- "${cmd[@]}")
  fi

  echo "----> ${cmd[*]}"
  exec "${cmd[@]}"
}

main "${@}"
