#!/bin/bash
cd "$(dirname "$0")/.."
[ $PORT ]     || PORT=5000
[ $RACK_ENV ] || RACK_ENV=development

cmd="bundle exec je puma -I lib -p $PORT -t ${PUMA_MIN_THREADS:-8}:${PUMA_MAX_THREADS:-12} -w ${PUMA_WORKERS:-2}"
[[ $RACK_ENV == "development" ]] && exec rerun -p '**/*.{rb,ru}' "$cmd"
exec $cmd
