#!/bin/bash

GIT_ROOT="$(git rev-parse --show-toplevel)"

[[ -f "$GIT_ROOT"/.example.env ]] \
  && source "$GIT_ROOT"/.example.env

: ${TRAVIS_BUILD_APP_HOST:-localhost:8080}
PORT=${TRAVIS_BUILD_APP_HOST##*:}

cmd="bundle exec rackup -I lib -p ${PORT:-8080}"
[[ "$RACK_ENV" == "development" ]] && \
  exec rerun -p '**/*.{rb,ru,sh,erb,conf}' "$cmd"
exec $cmd
