#!/bin/bash
set -o errexit

main() {
  : "${GITHUB_OAUTH_TOKEN:=${no_scope_token}}"

  local top
  top="$(git rev-parse --show-toplevel)"
  cd "${top}"

  docker-compose up -d
  sleep 10
  docker ps -a
  docker logs travisbuild_web_1

  local e=0
  for f in example_payloads/*.json; do
    echo "${f##*/}"
    curl -sf -X POST -d "@${f}" localhost:4000/script >/dev/null || e=$((e + 1))
  done
  test "${e}" -eq 0
}

main "${@}"
