#!/bin/bash

set -ev

e=0
for f in examples/*.sh.txt; do
  echo "checking bash syntax $f"
  bash -n $f || let e=$e+1
  if [[ $f = examples/addon* ]]; then
    continue
  fi
  echo "checking bash syntax for stage functions in $f"
  sed -e '1,/START_FUNCS/ d' $f | sed -e '/END_FUNCS/,$ d' > ${f%*.txt}
  rm -f ~/.travis/job_stages
  bash -c "source ${f%*.txt}; if [[ -f ~/.travis/job_stages ]]; then source ~/.travis/job_stages; fi" || let e=$e+1
done
test $e -eq 0

e=0
mkdir -p $HOME/.travis
for f in examples/*-integration-*.sh.txt; do
  cat > $HOME/.travis/job_stages < /dev/null
  sed -i '/^source $HOME\/\.travis\/job_stages/,$d' $f
  bash --norc -c "source $f && source $HOME/.travis/job_stages || exit 1" || let e=$e+1
done
test $e -eq 0
